pipeline {
    agent any
    
    stages {
        stage('config') {
            steps {
                sh 'aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 299367009966.dkr.ecr.us-east-1.amazonaws.com'
            }
        }
        stage('frontend') {
            steps {
                sh 'cd frontend && docker build -t project-1:frontend .'
                sh 'docker tag project-1:frontend 010526286234.dkr.ecr.us-east-1.amazonaws.com/project-1:frontend'
                sh 'docker push 010526286234.dkr.ecr.us-east-1.amazonaws.com/project-1:frontend'
                sh 'aws ecs update-service --cluster light-feather-cluster --service frontend-service --force-new-deployment'
            }
        }
        stage('backend') {
            steps {
                sh 'cd backend && docker build -t project-1:backend .'
                sh 'docker tag project-1:backend 010526286234.dkr.ecr.us-east-1.amazonaws.com/project-1:backend'
                sh 'docker push 010526286234.dkr.ecr.us-east-1.amazonaws.com/project-1:backend'
                sh 'aws ecs update-service --cluster light-feather-cluster --service backend-service --force-new-deployment'

            }
        }
    }
}
